"""Optimizer-step examples (category "block", tag "optimization") — one
iteration/step of classic iterative algorithms, whole-block graphs.

Each example is ONE step of an iterative algorithm (PSO, k-means, ALS,
conjugate gradient, power iteration, softmax regression), staged as an
ordinary ``@etl.defn`` graph: forward-only, no ``etl.grad``, no control
flow, no loops — the step's formulas are expressed directly with ``etl``
ops, and the numpy reference mirrors the EXACT same arithmetic (same op
order, same fp32 constants), so the strict conformance defaults pass — most
steps are bit-identical to their reference.

Per-example formulas:

- ``pso_step``:  v_new = w*v + c1*r1*(pb - p) + c2*r2*(gb - p);
                 p_new = p + v_new.  The PSO coefficients w, c1, c2 AND the
                 pseudo-random draws r1, r2 are STATIC Python floats — a
                 documented, deliberate choice: fixed coefficients make the
                 step fully deterministic (reproducible without an RNG
                 input); the draw quality is irrelevant for a single-step
                 conformance check.
- ``kmeans_iter``: assignments = argmin_k |x_i - c_k|^2 (etl.argmin);
                 new centroid k = sum_i(x_i * [a_i == k]) / max(count_k, 1)
                 via a trace-time one-hot loop over k (K is a static
                 constant) — the ``max(count, 1)`` guard pins the
                 empty-cluster convention to the zero vector (documented:
                 some random seeds leave a cluster empty, e.g. seed 3 with
                 N=64, K=8).
- ``als_step``: one alternating-least-squares half-step updating the user
                 factor U against the fixed item factor V and the dense
                 target X:  U_new^T = solve(V V^T, V X^T),  U_new =
                 (U_new^T)^T  (etl.solve; V standard-normal [K,N] makes
                 V V^T positive definite, so the solve is well-posed).
- ``cg_step``:  alpha = r·r / (p·A p);  x_new = x + alpha p;
                 r_new = r - alpha A p;  beta = r_new·r_new / (r·r);
                 p_new = r_new + beta p.  A is generated SPD via
                 ``inputs_fn`` (M M^T + N I) so p·A p > 0 for any seed.
- ``power_iter``: v_new = A v / |A v|  (normalize by sqrt of sum of
                 squares).  A is generated SPD via ``inputs_fn`` so A v = 0
                 only if v = 0 (v is standard-normal — never zero), keeping
                 the normalization well-defined for any seed.
- ``softmax_reg_step``: one gradient-descent step of softmax regression
                 (gradients written out explicitly — no etl.grad):
                 yhat = softmax(x W + b);  grad_W = x^T (yhat - y) / N;
                 grad_b = sum(yhat - y, axis=0) / N;  W_new = W - lr*grad_W;
                 b_new = b - lr*grad_b;  loss = -(1/N) sum(y * log yhat)
                 computed in the numerically stable log-sum-exp form
                 (logits - max - log(sum(exp(logits - max)))).  y is a
                 one-hot label matrix generated by ``inputs_fn``.

StableHLO export notes (all explicit v1 deferrals — the numpy backend is
unaffected; these examples are validated on numpy only): ``argmin``
(``kmeans_iter``) and ``gather``/``scatter`` are in the StableHLO writer's
``DEFERRED_OPS`` (no StableHLO argmin; gather/scatter deferred), and
``solve`` (``als_step``) has no StableHLO mapping — each raises
``core.BackendError`` naming the op at export/lower time. ``kmeans_iter``
uses the one-hot reduction formulation (a trace-time static loop over K)
instead of ``etl.gather``/``etl.scatter`` aggregation — it traces most
cleanly and needs no scatter-accumulate op.
"""
from __future__ import annotations

import numpy as np

import etl
from etl import TensorSpec, defn

from .base import Example, _F32, register_all

# --- pso_step ----------------------------------------------------------------
# One PSO iteration. w, c1, c2, r1, r2 are static Python floats (see module
# docstring: deterministic, documented choice).

_PSO_N, _PSO_D = 32, 4

_PSO_W, _PSO_C1, _PSO_C2, _PSO_R1, _PSO_R2 = 0.9, 2.0, 2.0, 0.5, 0.7
_PSO_C1R1 = _PSO_C1 * _PSO_R1  # 1.0
_PSO_C2R2 = _PSO_C2 * _PSO_R2  # 1.4


@defn
def _pso_step_graph(p, v, pb, gb):
    v_new = etl.add(
        etl.add(
            etl.multiply(v, _PSO_W),
            etl.multiply(etl.subtract(pb, p), _PSO_C1R1),
        ),
        etl.multiply(etl.subtract(gb, p), _PSO_C2R2),
    )
    p_new = etl.add(p, v_new)
    return v_new, p_new


def _pso_step_numpy(inputs):
    p, v, pb, gb = inputs
    w_f = np.float32(_PSO_W)
    c1r1_f = np.float32(_PSO_C1R1)
    c2r2_f = np.float32(_PSO_C2R2)
    v_new = w_f * v + c1r1_f * (pb - p) + c2r2_f * (gb - p)
    return v_new, p + v_new


# --- kmeans_iter -------------------------------------------------------------
# One k-means iteration: squared-distance argmin assignments, then per-cluster
# means via a trace-time one-hot loop over K. Empty clusters keep the zero
# vector (max(count, 1) denominator — documented convention).

_KMEANS_N, _KMEANS_D, _KMEANS_K = 64, 8, 8


@defn
def _kmeans_iter_graph(x, c):
    xr = etl.reshape(x, (_KMEANS_N, 1, _KMEANS_D))
    cr = etl.reshape(c, (1, _KMEANS_K, _KMEANS_D))
    diff = etl.subtract(xr, cr)
    d2 = etl.sum(etl.multiply(diff, diff), axes=-1)  # [N,K]
    assignments = etl.argmin(d2, axis=1)  # [N] int64
    parts = []
    for k in range(_KMEANS_K):
        mask = etl.cast(etl.equal(assignments, k), _F32)  # [N]
        sums = etl.sum(etl.multiply(x, etl.reshape(mask, (_KMEANS_N, 1))),
                       axes=0)  # [D]
        cnt = etl.maximum(etl.sum(mask, axes=0, keepdims=True), 1.0)  # [1]
        parts.append(etl.reshape(etl.divide(sums, cnt), (1, _KMEANS_D)))
    new_centroids = etl.concatenate(parts, axis=0)  # [K,D]
    return assignments, new_centroids


def _kmeans_iter_numpy(inputs):
    x, c = inputs
    d2 = ((x[:, None, :] - c[None, :, :]) ** 2).sum(axis=-1)
    assignments = np.argmin(d2, axis=1)
    parts = []
    for k in range(c.shape[0]):
        mask = (assignments == k).astype(np.float32)
        sums = (x * mask[:, None]).sum(axis=0)
        cnt = np.maximum(mask.sum(), 1.0)
        parts.append(sums / cnt)
    return assignments, np.stack(parts)


# --- als_step ----------------------------------------------------------------
# One ALS half-step: U_new^T = solve(V V^T, V X^T) with V (item factor) fixed.

_ALS_M, _ALS_N, _ALS_K = 24, 16, 8


@defn
def _als_step_graph(x, v):
    vvt = etl.dot(v, etl.transpose(v, (1, 0)))  # [K,K]
    vxt = etl.dot(v, etl.transpose(x, (1, 0)))  # [K,M]
    return etl.transpose(etl.solve(vvt, vxt), (1, 0))  # [M,K]


def _als_step_numpy(inputs):
    x, v = inputs
    return np.linalg.solve(v @ v.T, v @ x.T).T


# --- cg_step -----------------------------------------------------------------
# One conjugate-gradient step (SPD A via inputs_fn so p·A p > 0 always).

_CG_N = 16


def _cg_inputs(seed):
    rng = np.random.default_rng(seed)
    x = rng.standard_normal(_CG_N).astype(_F32)
    r = rng.standard_normal(_CG_N).astype(_F32)
    p = rng.standard_normal(_CG_N).astype(_F32)
    m = rng.standard_normal((_CG_N, _CG_N)).astype(_F32)
    a = (m @ m.T + _CG_N * np.eye(_CG_N)).astype(_F32)
    return [x, r, p, a]


@defn
def _cg_step_graph(x, r, p, a):
    ap = etl.reshape(etl.dot(a, etl.reshape(p, (_CG_N, 1))), (_CG_N,))
    rr = etl.sum(etl.multiply(r, r))
    alpha = etl.divide(rr, etl.sum(etl.multiply(p, ap)))
    x_new = etl.add(x, etl.multiply(alpha, p))
    r_new = etl.subtract(r, etl.multiply(alpha, ap))
    beta = etl.divide(etl.sum(etl.multiply(r_new, r_new)), rr)
    p_new = etl.add(r_new, etl.multiply(beta, p))
    return x_new, r_new, p_new


def _cg_step_numpy(inputs):
    x, r, p, a = inputs
    ap = a @ p
    rr = (r * r).sum()
    alpha = rr / (p * ap).sum()
    x_new = x + alpha * p
    r_new = r - alpha * ap
    beta = (r_new * r_new).sum() / rr
    p_new = r_new + beta * p
    return x_new, r_new, p_new


# --- power_iter --------------------------------------------------------------
# One power-iteration step: v_new = A v / |A v| (SPD A via inputs_fn keeps the
# normalization well-defined for any seed).

_PI_N = 16


def _power_iter_inputs(seed):
    rng = np.random.default_rng(seed)
    v = rng.standard_normal(_PI_N).astype(_F32)
    m = rng.standard_normal((_PI_N, _PI_N)).astype(_F32)
    a = (m @ m.T + _PI_N * np.eye(_PI_N)).astype(_F32)
    return [v, a]


@defn
def _power_iter_graph(v, a):
    av = etl.reshape(etl.dot(a, etl.reshape(v, (_PI_N, 1))), (_PI_N,))
    norm = etl.sqrt(etl.sum(etl.multiply(av, av)))
    return etl.divide(av, norm)


def _power_iter_numpy(inputs):
    v, a = inputs
    av = a @ v
    return av / np.sqrt((av * av).sum())


# --- softmax_reg_step --------------------------------------------------------
# One softmax-regression gradient-descent step with EXPLICIT gradient formulas
# (no etl.grad): grad_W = x^T (yhat - y) / N, grad_b = mean(yhat - y).
# y is a one-hot label matrix (inputs_fn). loss is the cross-entropy
# -(1/N) sum(y * log yhat) in the stable log-sum-exp form.

_SR_N, _SR_D, _SR_C = 32, 8, 4
_SR_LR = 0.1


def _softmax_reg_inputs(seed):
    rng = np.random.default_rng(seed)
    x = rng.standard_normal((_SR_N, _SR_D)).astype(_F32)
    labels = rng.integers(0, _SR_C, size=_SR_N)
    y = np.eye(_SR_C)[labels].astype(_F32)
    w = rng.standard_normal((_SR_D, _SR_C)).astype(_F32)
    b = rng.standard_normal(_SR_C).astype(_F32)
    return [x, y, w, b]


@defn
def _softmax_reg_step_graph(x, y, w, b):
    logits = etl.add(etl.dot(x, w), b)  # [N,C]
    m = etl.max(logits, axes=-1, keepdims=True)
    e = etl.exp(etl.subtract(logits, m))
    e_sum = etl.sum(e, axes=-1, keepdims=True)
    yhat = etl.divide(e, e_sum)
    diff = etl.subtract(yhat, y)  # [N,C]
    grad_w = etl.divide(etl.dot(etl.transpose(x, (1, 0)), diff), _SR_N)  # [D,C]
    grad_b = etl.divide(etl.sum(diff, axes=0), _SR_N)  # [C]
    w_new = etl.subtract(w, etl.multiply(grad_w, _SR_LR))
    b_new = etl.subtract(b, etl.multiply(grad_b, _SR_LR))
    # loss = -(1/N) * sum(y * (logits - logsumexp(logits))), 0-d scalar
    lse = etl.add(m, etl.log(e_sum))
    loss = etl.negate(etl.divide(
        etl.sum(etl.multiply(y, etl.subtract(logits, lse))), _SR_N))
    return w_new, b_new, loss


def _softmax_reg_numpy(inputs):
    x, y, w, b = inputs
    logits = x @ w + b
    m = logits.max(axis=-1, keepdims=True)
    e = np.exp(logits - m)
    e_sum = e.sum(axis=-1, keepdims=True)
    yhat = e / e_sum
    diff = yhat - y
    grad_w = (x.T @ diff) / _SR_N
    grad_b = diff.sum(axis=0) / _SR_N
    w_new = w - _SR_LR * grad_w
    b_new = b - _SR_LR * grad_b
    lse = m + np.log(e_sum)
    loss = -(y * (logits - lse)).sum() / _SR_N
    return w_new, b_new, np.asarray(loss)


# ---------------------------------------------------------------------------
# Registry (category "block", tag "optimization")
# ---------------------------------------------------------------------------

register_all([
    Example(
        name="pso_step",
        description="one PSO iteration: v' = w v + c1 r1 (pb-p) + c2 r2 (gb-p),"
                    " p' = p + v' (static w/c1/c2/r1/r2)",
        specs=(
            TensorSpec((_PSO_N, _PSO_D), _F32),
            TensorSpec((_PSO_N, _PSO_D), _F32),
            TensorSpec((_PSO_N, _PSO_D), _F32),
            TensorSpec((_PSO_D,), _F32),
        ),
        graph=_pso_step_graph,
        numpy_ref=_pso_step_numpy,
        category="block",
        tags=("optimization",),
    ),
    Example(
        name="kmeans_iter",
        description="one k-means iteration: argmin squared-distance assignments"
                    " + per-cluster mean centroids (empty cluster -> zero"
                    " vector)",
        specs=(
            TensorSpec((_KMEANS_N, _KMEANS_D), _F32),
            TensorSpec((_KMEANS_K, _KMEANS_D), _F32),
        ),
        graph=_kmeans_iter_graph,
        numpy_ref=_kmeans_iter_numpy,
        category="block",
        tags=("optimization",),
    ),
    Example(
        name="als_step",
        description="one ALS half-step: U'^T = solve(V V^T, V X^T) with item"
                    " factor V fixed (etl.solve)",
        specs=(
            TensorSpec((_ALS_M, _ALS_N), _F32),
            TensorSpec((_ALS_K, _ALS_N), _F32),
        ),
        graph=_als_step_graph,
        numpy_ref=_als_step_numpy,
        category="block",
        tags=("optimization",),
    ),
    Example(
        name="cg_step",
        description="one conjugate-gradient step on SPD A: alpha/beta line"
                    " search updating (x, r, p)",
        specs=(
            TensorSpec((_CG_N,), _F32),
            TensorSpec((_CG_N,), _F32),
            TensorSpec((_CG_N,), _F32),
            TensorSpec((_CG_N, _CG_N), _F32),
        ),
        graph=_cg_step_graph,
        numpy_ref=_cg_step_numpy,
        inputs_fn=_cg_inputs,
        category="block",
        tags=("optimization",),
    ),
    Example(
        name="power_iter",
        description="one power-iteration step: v' = A v / |A v| on SPD A",
        specs=(
            TensorSpec((_PI_N,), _F32),
            TensorSpec((_PI_N, _PI_N), _F32),
        ),
        graph=_power_iter_graph,
        numpy_ref=_power_iter_numpy,
        inputs_fn=_power_iter_inputs,
        category="block",
        tags=("optimization",),
    ),
    Example(
        name="softmax_reg_step",
        description="one softmax-regression GD step (explicit grads):"
                    " W' = W - lr x^T(yhat-y)/N, b' = b - lr mean(yhat-y), +"
                    " cross-entropy loss",
        specs=(
            TensorSpec((_SR_N, _SR_D), _F32),
            TensorSpec((_SR_N, _SR_C), _F32),
            TensorSpec((_SR_D, _SR_C), _F32),
            TensorSpec((_SR_C,), _F32),
        ),
        graph=_softmax_reg_step_graph,
        numpy_ref=_softmax_reg_numpy,
        inputs_fn=_softmax_reg_inputs,
        category="block",
        tags=("optimization",),
    ),
])
